name: components
description: Common widgets and templates
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.0.0

dependencies:
  cancellation:
    git: https://github.com/lamtx/cancellation.git
  ext:
    git: https://github.com/lamtx/ext.git
  flutter:
    sdk: flutter
  get_it: ^8.0.0
  meta:
  provider: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: