name: components
description: Common widgets and templates
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^2.12.0-0

dependencies:
  ext:
    git: https://github.com/lamtx/ext.git
  flutter:
    sdk: flutter
  meta:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: